---
# Role to install Logstash 6.x
# If elasticsearch role is skipped, copy the pre-reqs of adding elastic apt-repo required here.

- name: Install Logstash with yum
  yum:
   name: logstash
   update_cache: yes
  when: (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "8")

- name: Copy the default logstash config
  template:
    src: logstash_main.conf.j2
    dest: /etc/logstash/main.conf
    owner: root
    group: root
    mode: 0644

- name: Permit Traffic on Port 9600/tcp
  firewalld:
    port: 9600/tcp
    permanent: true
    state: enabled
  when: (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "8")

- name: Starting Logstash as a service
  service:
   name: logstash
   state: started
   enabled: yes
