---
# Role to install Grafana 5.x

- name: Download Grafana GPG Key
  get_url:
    url: "https://packages.grafana.com/gpg.key"
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-grafana

- name: Install YUM Utils (needed for yum-config-manager)
  package:
    name: yum-utils
    state: present
  when: (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "8")

- name: Add Grafana YUM Repository
  yum_repository:
    name: grafana
    description: Grafana Stable Repository
    baseurl: https://packages.grafana.com/oss/rpm
    gpgcheck: 1
    enabled: 1
    gpgkey: https://packages.grafana.com/gpg.key
  when: (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "8")

- name: Install Grafana
  yum:
    name: grafana
    update_cache: yes
  when: (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "8")

- name: Permit Traffic on Port 3000/tcp
  firewalld:
    port: 3000/tcp
    permanent: true
    state: enabled
  when: (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "8")

- name: Starting Grafana as a service
  service:
      name: grafana-server
      state: started
      enabled: yes
