---
# Role to install Kibana 6.x
# If elasticsearch role is skipped, copy the pre-reqs of adding elastic apt-repo required here.

- name: Install Kibana with apt
  yum:
   name: kibana
   update_cache: yes
  when: (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "8")

- name: Ensure Kibana binds only to localhost
  lineinfile:
   destfile: /etc/kibana/kibana.yml
   regexp: 'server.host:'
   line: 'server.host: {{kibana_host}}'

- name: Setting Kibana port address
  lineinfile:
   destfile: /etc/kibana/kibana.yml
   regexp: 'server.port:'
   line: 'server.port: {{kibana_port}}'

- name: Setting Elasticsearch URL in Kibana Config
  lineinfile:
   destfile: /etc/kibana/kibana.yml
   regexp: 'elasticsearch.url:'
   line: 'elasticsearch.url: "http://{{elasticsearch_host}}:{{elasticsearch_port}}"'

- name: Permit Traffic on Port 5601/tcp
  firewalld:
    port: 5601/tcp
    permanent: true
    state: enabled
  when: (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "8")

- name: Starting Kibana as a service
  service:
   name: kibana
   state: started
   enabled: yes
