---
# Role to install alert_manager


- name: create alertmanager directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ alertmanager_config_dir }}"
    - "{{ alertmanager_config_dir }}/templates"
    - "{{ alertmanager_db_dir }}"

- name: download alertmanager binary to local folder
  become: false
  unarchive:
    src: "https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager_version }}/alertmanager-{{ alertmanager_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}.tar.gz"
    dest: "/tmp"
    remote_src: true
    creates: "/tmp/alertmanager-{{ alertmanager_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}/alertmanager"
  register: _download_binary
  until: _download_binary is succeeded
  retries: 5
  delay: 2
  # run_once: true
  delegate_to: localhost

- name: propagate alertmanager and amtool binaries
  copy:
    src: "/tmp/alertmanager-{{ alertmanager_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
  with_items:
    - alertmanager
    - amtool

- name: propagate alertmanager config file
  copy:
    src: "/tmp/alertmanager-{{ alertmanager_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}/{{ item }}"
    dest: "{{alertmanager_config_dir}}/{{item}}"
    mode: 0755
  with_items:
    - alertmanager.yml

- name: remove alertmanager binaries from old location
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /opt/alertmanager/alertmanager
    - /opt/alertmanager/amtool
    - /opt/alertmanager

- name: create systemd service unit
  template:
    src: alertmanager.service.j2
    dest: /etc/systemd/system/alertmanager.service
    owner: root
    group: root
    mode: 0644

- name: Permit Traffic on Port 9093/tcp
  firewalld:
    port: 9093/tcp
    permanent: true
    state: enabled
  when: (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "8") 

- name: Starting Alertmanager as a service
  service:
   name: alertmanager
   state: started
   enabled: yes
