---
# Role to install Elasticsearch 8.x

#- name: Upgrade all packages
#  yum:
#    name: '*'
#    state: latest

- name: Install the gnupg package
  yum:
    name: gnupg
    state: present
  when: (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "8")

- name: Import the Elasticsearch PGP Key
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Install yum-utils
  package:
    name: yum-utils
    state: present
    update_cache: yes
  when: (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "8")

- name: Add yum repo to source list
  yum_repository:
    name: elastic-8.x
    description: Elasticsearch 8.x Repository
    baseurl: https://artifacts.elastic.co/packages/8.x/yum
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: yes
  when: (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "8")

- name: Install Elasticsearch
  package:
   name: elasticsearch
     #gpgcheck: no
   state: present
   update_cache: yes

- name: Ensure elasticsearch binds only to localhost
  lineinfile:
   destfile: /etc/elasticsearch/elasticsearch.yml
   regexp: 'network.host:'
   line: 'network.host: "{{elasticsearch_host}}"'

- name: Setting Elasticsearch port address
  lineinfile:
   destfile: /etc/elasticsearch/elasticsearch.yml
   regexp: 'http.port:'
   line: 'http.port: {{elasticsearch_port}}'

- name: Permit Traffic on Port 9200/tcp
  firewalld:
    port: 9200/tcp
    permanent: true
    state: enabled
  when: (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "8")

- name: Starting Elasticsearch as a service
  service:
   name: elasticsearch
   state: started
   enabled: yes
